FROM debian:12

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y build-essential cmake git
RUN apt-get install -y vim zlib1g \
		       qtbase5-dev libminizip-dev libsdl2-dev # for fceux

RUN echo "alias ls='ls --color'" >> /root/.bashrc

WORKDIR /root
